services:
  movilizaciones:
    build: .
    container_name: asignacion_movilizaciones
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    extra_hosts:
      - "n8n.cramer.cl:192.9.200.12"
